// How each engine scales as brand themes are added.
//
// The arena app ships light/dark only, which is the one case every engine has a
// dedicated answer for. A site with a handful of brand themes is a different
// question: where do the extra bytes land, and does the first load pay for a
// theme nobody selected?
//
// For each theme count N this injects N generated themes into an engine's own
// multi-theme API — Bamboo `theme.variants`, Panda `themes`, StyleX
// `createTheme` — builds, and measures the stylesheet the browser downloads
// plus any theme artifact emitted beside it. Configs are restored afterwards.
//
// Every theme overrides the same 18 theme-aware colours in every engine, so a
// theme costs the same amount of authored intent everywhere and only the
// engine's encoding of it differs.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { brotliCompressSync, gzipSync } from "node:zlib";

import { ENGINES } from "./engines.mjs";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const COUNTS = [0, 1, 2, 4, 8];

/** The theme-aware colours all three apps declare. Derived colours are excluded:
 *  they resolve from these, so a theme that overrides these moves them too. */
const COLORS = [
  "bg", "surface", "surface2", "surface3", "border", "borderStrong",
  "text", "muted", "faint", "accent", "accentSoft", "accentContrast",
  "success", "successSoft", "warning", "warningSoft", "danger", "dangerSoft",
];

const NAMES = ["ocean", "forest", "sunset", "plum", "slate", "amber", "rose", "moss"];

/** Deterministic, distinct, and valid hex. The values are never rendered — only
 *  their byte cost is measured — but they must differ per theme so no engine can
 *  collapse two themes into one declaration. */
const hex = (themeIndex, tokenIndex, dark) => {
  const seed = (themeIndex * 37 + tokenIndex * 11 + (dark ? 7 : 0)) % 216;
  const r = 40 + ((seed * 7) % 190);
  const g = 40 + ((seed * 13) % 190);
  const b = 40 + ((seed * 29) % 190);
  const c = (n) => n.toString(16).padStart(2, "0");
  return dark ? `#${c(r >> 1)}${c(g >> 1)}${c(b >> 1)}` : `#${c(r)}${c(g)}${c(b)}`;
};

const themeNames = (n) => NAMES.slice(0, n);

/* -----------------------------------------------------------------------------
 * Per-engine injection. Each writes N themes using that engine's own API.
 * -----------------------------------------------------------------------------*/

const bambooThemes = (n) => {
  if (!n) return "";
  const body = themeNames(n)
    .map((name, ti) => {
      const colors = COLORS.map(
        (c, i) => `            ${c}: { value: { base: "${hex(ti, i, false)}", _osDark: "${hex(ti, i, true)}" } },`,
      ).join("\n");
      return `      ${name}: {\n        semanticTokens: {\n          colors: {\n${colors}\n          },\n        },\n      },`;
    })
    .join("\n");
  return `    variants: {\n${body}\n    },\n`;
};

const pandaThemes = (n) => {
  if (!n) return "";
  const body = themeNames(n)
    .map((name, ti) => {
      const colors = COLORS.map(
        (c, i) =>
          `          ${c}: { value: { base: "${hex(ti, i, false)}", _osDark: "${hex(ti, i, true)}", _light: "${hex(ti, i, false)}", _dark: "${hex(ti, i, true)}" } },`,
      ).join("\n");
      return `    ${name}: {\n      semanticTokens: {\n        colors: {\n${colors}\n        },\n      },\n    },`;
    })
    .join("\n");
  return `  themes: {\n${body}\n  },\n`;
};

const stylexThemes = (n) => {
  if (!n) return "";
  const defs = themeNames(n)
    .map((name, ti) => {
      // Same intent as the other two engines: a brand theme that still answers
      // the system dark preference. Light values alone would understate the cost.
      const colors = COLORS.map(
        (c, i) => `  ${c}: { default: "${hex(ti, i, false)}", [DARK]: "${hex(ti, i, true)}" },`,
      ).join("\n");
      return `export const ${name}Theme = stylex.createTheme(t, {\n${colors}\n});`;
    })
    .join("\n\n");
  // StyleX drops a theme nothing imports, so the generated themes are collected
  // into one exported array and that array is re-exported from the app's own
  // theme module. Without the reference the measurement would read zero.
  const list = themeNames(n).map((name) => `${name}Theme`).join(", ");
  return `\n\n/* generated by tools/theming.mjs */\nconst DARK = "@media (prefers-color-scheme: dark)";\n\n${defs}\n\nexport const brandThemes = [${list}];\n`;
};

// Truss has no multi-theme API. Its documented answer is CSS custom
// properties: the palette reads `var(--bg)` and a theme is a selector block
// that redefines the variables, written as raw CSS in a `.css.ts` module. That
// is what a Truss user would ship, so it is what gets measured; the absence of
// a dedicated API is part of the finding.
const trussThemes = (n) => {
  if (!n) return "";
  return themeNames(n)
    .map((name, ti) => {
      const vars = COLORS.map(
        (c, i) => `    --${kebab(c)}: light-dark(${hex(ti, i, false)}, ${hex(ti, i, true)});`,
      ).join("\n");
      return `  '[data-theme="${name}"]': Css.raw\`\n${vars}\n  \`,`;
    })
    .join("\n");
};

// Tailwind has no multi-theme API either. `@theme` defines one theme; the
// documented answer for a second is to redefine the custom properties under a
// selector, which is what the app's palette already reads through. So a brand
// theme is a plain CSS block appended to app.css — the same shape as the Truss
// one, and the same finding: no dedicated API to measure.
const tailwindThemes = (n) => {
  if (!n) return "";
  const blocks = themeNames(n)
    .map((name, ti) => {
      const vars = COLORS.map(
        (c, i) => `  --${kebab(c)}: light-dark(${hex(ti, i, false)}, ${hex(ti, i, true)});`,
      ).join("\n");
      return `[data-theme="${name}"] {\n${vars}\n}`;
    })
    .join("\n\n");
  return `\n/* generated by tools/theming.mjs */\n${blocks}\n`;
};

/** I.e. `borderStrong` → `border-strong`, matching the variable names in theme.css.ts. */
const kebab = (name) => name.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

/* -----------------------------------------------------------------------------
 * Applying and restoring
 * -----------------------------------------------------------------------------*/

const targets = {
  bamboo: (dir) => join(dir, "bamboo.config.ts"),
  panda: (dir) => join(dir, "panda.config.ts"),
  stylex: (dir) => join(dir, "app/themes.stylex.ts"),
  truss: (dir) => join(dir, "app/theme.css.ts"),
  tailwind: (dir) => join(dir, "app/app.css"),
};

const apply = (engine, dir, n) => {
  const file = targets[engine](dir);
  const original = readFileSync(file, "utf8");

  let next;
  if (engine === "bamboo") {
    next = original.replace("  theme: {\n", `  theme: {\n${bambooThemes(n)}`);
  } else if (engine === "panda") {
    next = original.replace("export default defineConfig({\n", `export default defineConfig({\n${pandaThemes(n)}`);
  } else if (engine === "truss") {
    next = n ? original.replace(/\n};\n$/, `\n${trussThemes(n)}\n};\n`) : original;
  } else if (engine === "tailwind") {
    next = n ? original + tailwindThemes(n) : original;
  } else {
    next = original + stylexThemes(n);
  }

  if (n && next === original) throw new Error(`${engine}: injection anchor not found in ${file}`);
  writeFileSync(file, next);
  return () => writeFileSync(file, original);
};

/* -----------------------------------------------------------------------------
 * Measuring
 * -----------------------------------------------------------------------------*/

const sizes = (buf) => ({
  raw: buf.length,
  gzip: gzipSync(buf, { level: 9 }).length,
  brotli: brotliCompressSync(buf).length,
});

const measure = (dir) => {
  const assets = join(dir, "build/client/assets");
  const css = readdirSync(assets)
    .filter((f) => f.endsWith(".css"))
    .map((f) => join(assets, f));

  // The stylesheet the document links. StyleX also emits an unreferenced
  // duplicate, so the largest is the one that counts.
  const sheet = css.map((f) => readFileSync(f)).sort((a, b) => b.length - a.length)[0] ?? Buffer.alloc(0);

  // Theme artifacts loaded on demand rather than linked by the document.
  const themeDir = join(dir, "styled-system/themes");
  let artifacts = 0;
  let artifactCount = 0;
  if (existsSync(themeDir)) {
    for (const f of readdirSync(themeDir)) {
      if (!/^theme-.*\.json$/.test(f)) continue;
      artifacts += statSync(join(themeDir, f)).size;
      artifactCount += 1;
    }
  }

  return { sheet: sizes(sheet), artifacts, artifactCount };
};

const build = (dir) => {
  execFileSync("npm", ["run", "build"], { cwd: dir, stdio: "pipe", encoding: "utf8" });
};

/* -----------------------------------------------------------------------------
 * Run
 * -----------------------------------------------------------------------------*/

const results = {};

for (const { name } of ENGINES) {
  const dir = join(ROOT, "apps", name);
  results[name] = [];

  for (const n of COUNTS) {
    // A stale themes/ directory from a previous count would be counted again.
    rmSync(join(dir, "styled-system/themes"), { recursive: true, force: true });

    const restore = apply(name, dir, n);
    try {
      build(dir);
      results[name].push({ n, ...measure(dir) });
      process.stderr.write(`  ${name} n=${n} ok\n`);
    } catch (error) {
      results[name].push({ n, failed: String(error.stderr || error.message).slice(0, 200) });
      process.stderr.write(`  ${name} n=${n} FAILED\n`);
    } finally {
      restore();
    }
  }

  // Leave the tree as it was found: rebuild at the committed config.
  rmSync(join(dir, "styled-system/themes"), { recursive: true, force: true });
  build(dir);
}

/* -----------------------------------------------------------------------------
 * Report
 * -----------------------------------------------------------------------------*/

const pad = (s, w) => String(s).padStart(w);

console.log("\n================ THEME SCALING ================\n");
console.log(`  ${COLORS.length} colours overridden per theme, in each engine's own multi-theme API.\n`);

for (const [name, rows] of Object.entries(results)) {
  console.log(`${name}:`);
  console.log("    themes   stylesheet raw   gzip   brotli   theme artifacts");
  for (const r of rows) {
    if (r.failed) {
      console.log(`  ${pad(r.n, 7)}   BUILD FAILED — ${r.failed.split("\n")[0]}`);
      continue;
    }
    const art = r.artifactCount ? `${r.artifacts} B in ${r.artifactCount} file(s)` : "—";
    console.log(
      `  ${pad(r.n, 7)}   ${pad(r.sheet.raw, 14)}   ${pad(r.sheet.gzip, 4)}   ${pad(r.sheet.brotli, 6)}   ${art}`,
    );
  }

  const ok = rows.filter((r) => !r.failed);
  const base = ok.find((r) => r.n === 0);
  const top = ok[ok.length - 1];
  if (base && top && top.n > 0) {
    const perTheme = (top.sheet.brotli - base.sheet.brotli) / top.n;
    console.log(
      `    → ${perTheme.toFixed(0)} B brotli added to the downloaded stylesheet per theme` +
        (top.artifactCount ? `, plus ${(top.artifacts / top.n).toFixed(0)} B per lazy artifact` : ""),
    );
  }
  console.log("");
}
